### ISSUE TITLE
`score_variants` Skip variants unable to annotate

### ISSUE THREAD

**Issue by Avsecz** [kipoi/kipoi#264]
Currently, the annotation pipeline breaks if an indel is encountered. Desired behaviour would be to return NA or something similar in the field for the INDEL. That way, the user doesn't have to prepare the SNP-only vcf themselves

Example where it breaks on a deletion: https://github.com/kipoi/kipoi/blob/master/kipoi/postprocessing/variant_effects/utils/generic.py#L553

**Comment by krrome** [comment]
can only break if you don't use the dedicated functions for variant-centered region generation or variant-region overlaps in the annotation pipeline. Those two ensure that no indel is processed. There are several steps where indels can make problems, so I prefer to have the indel removal at the very first level when actually loading records from the VCF, rather than in all subsequent methods. Please give an example where the pipeline fails.

**Comment by krrome** [comment]
@Avsecz would be good to hear your opinion on whether I should validate that it's not an indel at every step (where it is a requirement)...

**Comment by Avsecz** [comment]
The problem arose when ALT="."

**Comment by krrome** [comment]
hmm, good point. didn't know that "." was a valid entry for ALT, but makes sense. Will fix that in the open PR

**Comment by krrome** [comment]
after checking the definition "." in "REF" nor in "ALT" is not part of the VCF definition: https://samtools.github.io/hts-specs/VCFv4.1.pdf 
see also Brent Pedersen's intepretation: brentp/cyvcf2#82

**Comment by Avsecz** [comment]
Funny. I observed it im the clinvar vcf file
