### ISSUE TITLE
Meaning of the test data's result from kipoi

### ISSUE THREAD

**Issue by yuetang625-UT** [kipoi/kipoi#469]
hi, I used the kipoi version of basenji and got the results like this.
![image](https://user-images.githubusercontent.com/54342920/66687239-9f3e3c80-ec47-11e9-80e5-7d63a7474b83.png)
I knew the meaning of the preds/m/n, but what did the specific number mean in the pic above? there are lots of data for this small test data, Is it the expression results of each region on a different sample, I need to add them up in order to obtain a final prediction level? or it is just a score? If I want to know the expression level of specific genes, do you have any suggestions for me with basenji?

**Comment by Avsecz** [comment]
Hi, have a look at the following issue: https://github.com/kipoi/models/issues/87

**Comment by yuetang625-UT** [comment]
yes, I looked at that issue. But my question is what's the meaning of the matrix results?  I think this module helps me predict the expression level of the region which I am interested in, is it correct? But for the result, preds/n/m, m is the track, but there are too many n, if I want to get an expression result, how to deal with this preds/n/m matrix?

**Comment by Avsecz** [comment]
Yes. The model predicts CAGE counts at 128 bp resolution for different tissues among other genomic features (DNase accessibility). CAGE counts at TSS of a gene is a good proxy for gene expression. So basically you need to generate intervals centered at the TSS and then take the slice of the array at the central position (maybe center + 1) as well as subset to the features corresponding to CAGE features. Since that functionality is not implemented in Kipoi I recommend that you have a look at the original Basenji package https://github.com/calico/basenji/blob/master/tutorials/genes.ipynb.

**Comment by yuetang625-UT** [comment]
Thanks, that makes sense. So it means that the expression results that I got from kipoi is a 128bp resolution result? Which is corresponding to the n in the preds/n/m? Hence, if I want to obtain an expression of a TSS, I need to transfer these ns in preds/n/m into one number? BTW, the training dataset for kipoi is https://storage.googleapis.com/131k/sample_wigs.txt?

**Comment by Avsecz** [comment]
Yes. Exactly. This txt file will help you subset the feature axis (the one with 4k values, e.g. `m`). For `n` I guess you can take only the ones where n = 960 / 2 = 480. Note that you might have to take the 481th value depending on how you center the provided interval.

**Comment by yuetang625-UT** [comment]
OK, got it. Thanks for your help.
