### ISSUE TITLE
package kipoi with conda

### ISSUE THREAD

**Issue by Avsecz** [kipoi/kipoi#94]
Since we are using pybedtools installed from conda, it would be nice to package kipoi also with conda

**Comment by visze** [comment]
I think it is highly recommended to pack kipoi also with conda. Especially because kipoi use conda a lot "under the hood". 

The best place will be [bioconda](https://bioconda.github.io).

I created an initial recipe that should work, make a PR but didn't merge it yet. You can see the PR here: https://github.com/bioconda/bioconda-recipes/pull/8266
I had to trick a bit with the packages `related>=0.6.0`  and `enum34` because both were not available in conda.

If you agree on it I will merge it into bioconda. Also I need to update the recipe to the 0.2.9 version. 

What do you think?

**Comment by Avsecz** [comment]
I think putting kipoi to bioconda or conda-forge is a great idea. Thanks for making the PR! I added a minor comment to the PR.

I think the biggest benefit from using bioconda (and not conda-forge) would be if we also installed the '[vep]' dependencies: https://github.com/kipoi/kipoi/blob/master/setup.py#L57. I find it much easier to install tools like pybedtools from bioconda. [Here](https://github.com/kipoi/kipoi/blob/master/.circleci/Dockerfile) is for example the Dockerfile for Kipoo's test environment. 

Do you think it makes sense to include the [vep] dependencies like pybedtools with bioconda? Or is there an equivalent in conda where one specifies the subpackages like `conda install -c bioconda kipoi[vep]`?

**Comment by visze** [comment]
Why not using the `ensembl-vep` package from bioconda. See https://bioconda.github.io/recipes/ensembl-vep/README.html

I think bioconda is the right place because
1. It is a software for the bioinformatics world
2. It is not possible to include libraries on bioconda into conda-forge. E.g, if we want to include vep we have to use bioconda. Bioconda depends on conda-forge but conda-forge not on bioconda...

@Avsecz Can't see your comment...

**Comment by Avsecz** [comment]
> Why not using the ensembl-vep package from bioconda. See https://bioconda.github.io/recipes/ensembl-vep/README.html

with `[vep]` I was referring to a set of dependencies in setup.py : https://github.com/kipoi/kipoi/blob/master/setup.py#L57-L63 (not including `ensembl-vep`).

> @Avsecz Can't see your comment...

oh. forgot to click 'submit review' :)

**Comment by Avsecz** [comment]
https://anaconda.org/bioconda/kipoi
